---
services:
  pgsql:
    image: postgres:16
    restart: unless-stopped
    environment:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    volumes:
      - ./data/pg:/var/lib/postgresql/data
    networks:
      - bot-network

  bot:
    restart: unless-stopped
    build:
      context: ./source
      dockerfile: Dockerfile
    volumes:
      - ./data/bot/application.properties:/app/config/application.properties:ro
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
